spring.application.name=auth-workflow

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_workflow
spring.datasource.username=auth_user
spring.datasource.password=auth_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=change-this-demo-secret-change-this-demo-secret
app.jwt.expiration=3600
